### ISSUE TITLE
Ability to write custom babel transformers via website

### ISSUE THREAD

**Issue by Memexurer** [j4k0xb/webcrack-ui#24]
something like https://astexplorer.net/ but better, like with autocompletion for babel etc
also would be cool if you could select transformer order on the website

**Comment by tecnessino** [comment]
yea it will be useful

**Comment by j4k0xb** [comment]
yeah I wanted to do something like this for a while, also with visualizing scope and [matchers](https://github.com/codemod-js/codemod/tree/main/packages/matchers)

but I don't see how it can be meaningfully integrated in this repo 🤔 , would rather create a new one
or do you have a special usecase?

**Comment by Memexurer** [comment]
i just needed some better tool than astexplorer for writing a deobfuscator, but your idea seems better to just create a new tool
